### ISSUE TITLE
A small wish for a installing Zabbix 

### ISSUE THREAD

**Issue by krotesk** [Trikke76/Zabbix-Book#10]
https://github.com/Trikke76/Zabbix-Book/blob/main/docs/installation/installing-zabbix.md#installing-zabbix-frontend-with-apache

Perhaps we should have added about SSL as well.

And maybe add some summary? Something like “Here we've set up our frontend and now let's move on to the topic of ...”.

**Comment by Trikke76** [comment]
Hi,

there was actually already a link to configure ssl but i just noticed it was missing for apache 
so i added the link to the topic for apache and added a conclusion

**Comment by Trikke76** [comment]
thx for the feedback

**Comment by krotesk** [comment]
@Trikke76 please read the mail from atsip-help[at]yandex[dot]ru
I have undertaken to translate into Russian.

**Comment by Trikke76** [comment]
hi,

sorry have not received any email
where did you sent it ? best to sent me PR 
however for translations i would suggest to wait a bit we are in the progress to see how we can create something more official so that zabbix and others can contribute and keep legal rights safe etc ...
If you are interested to be added as translator let me know then i contact you once everything is offical.
